export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const TOGGLE_PAUSE_MAIN_PLAYER = 'TOGGLE_PAUSE_MAIN_PLAYER';
export const CHANGE_SOUND_VOLUME = 'CHANGE_SOUND_VOLUME';
export const RESET_IS_PAUSED = 'RESET_IS_PAUSED';
